### PR TITLE
Feature/scale oss with num substations

### PR DESCRIPTION
**Pull request by Matt-Shields**
The existing structure only scales cost with the number of substations; this is a problem for larger plant sizes, which creates one huge substation.  This update also linearly scales the size of the substation based on the user-defined number of substations.

### CODE REVIEW

**Comment by Matt-Shields** [comment]
There are a few additional commits in here from the benchmarking branch that i started on; they're pretty benign, but i could also submit a separate PR with just the substation edits if preferable.

**Comment by JakeNunemaker** [comment]
Looks good to me - I had noticed some weird results in the past.

I removed some of the pycharm and packaging files and updated the .gitignore.

Do you need the Analysis files in the repo? I think it would be best to keep it to just code if possible, particularly now that we're porting this over to WISDEM on a regular basis.

**Comment by Matt-Shields** [comment]
Hey jake,

Good point - no, we don’t need the Analysis files. Want me to remove them and push a new commit?

Matt

Sent from my iPhone

On Mar 18, 2020, at 9:53 PM, Jake Nunemaker <notifications@github.com> wrote:

﻿

Looks good to me - I had noticed some weird results in the past.

I removed some of the pycharm and packaging files and updated the .gitignore.

Do you need the Analysis files in the repo? I think it would be best to keep it to just code if possible, particularly now that we're porting this over to WISDEM on a regular basis.

**Comment by JakeNunemaker** [comment]
I can remove them real quick and accept/merge the PR.

**Pull request merged**
