### PR TITLE
Design phase refactor

### PR DESCRIPTION
**Pull request by JakeNunemaker**
This PR modifies the aggregation of costs in ProjectManager so that DesignPhases are truly optional. Unit cost inputs are exposed at the InstallationPhase level and the costs to procure the systems are aggregated to `project.system_capex`. The installation costs of the subsystems is handled similarly to before and aggregated to `project.installation_capex`. These would be the two core outputs of the model.

Costs are then further aggregated to `bos_capex` (sum of system and installation capex) and eventually `total_capex` which includes project related costs (lease price, project financing, soft costs, turbine capex, etc.). See the attached flow diagram.

Screen Shot 2020-11-30 at 8 41 46 AM

I also removed the `ProjectDevelopment` phase and rolled the costs into optional inputs (with defaults) to `ProjectManager` itself.

@gbarter I added the new unit cost inputs to the WISDEM API with defaults. This will allow you to pass in the unit cost of monopiles, mooring lines, etc. and have them rolled into the total project capex.

### CODE REVIEW

**Comment by JakeNunemaker** [comment]
Closes #23

**Review by gbarter — APPROVED** [review]

**Comment by gbarter** [comment]
This is great!  This is definitely needed for WEIS and a number of other projects.  Will need to do some work on the WISDEM side to wire up all these new connections. I made some minor tweaks to a couple of lines in the ORBIT api file based on local updates within WISDEM.  We are actually nearing the point where WISDEM could rely on `pip install ORBIT` instead of embedding the code within the project. . . .

FYI: WISDEM has now adopted Black also, so no need to exempt it from your pre-commit hooks.

**Comment by JakeNunemaker** [comment]
@gbarter Is the only thing holding back a `pip install ORBIT` integration a new tagged release with these changes?

**Comment by gbarter** [comment]
No, definitely no need to add that stress to this PR.  WISDEM embedded its own version of ORBIT originally because of the rapid pace of changes on both sides, the need for additional customizations to work around certain behaviors, lack of packaging and package management, etc.  Those reasons are gradually slipping away, as is evidenced by this refactor, and the recent pip-ability of ORBIT.  I will have to take a closer look at the library contents before we stop duplicating the ORBIT code internally to WISDEM.  I think we have some more accommodations for larger turbines, but I'll have to double check.

**Comment by JakeNunemaker** [comment]
Ok I have another potential change coming up (#63) that might ease the interface between the two as well. And it will make it quicker. I'm not sure when I'll get to this though.

**Pull request merged**
