### PR TITLE
Enhancement/cable outputs

### PR DESCRIPTION
**Pull request by RHammond2**
This pull request adds:
 - the `save_layout` method to the `ArraySystemDesign` class to be able to easily customize default grid/ring setups
 - a flag to `plot_layout` in `ArraySystemDesign` to be return the `fig` and `ax` objects to futher annotate the layout plots
 - an update the `examples/custom_array_layout.ipynb` notebook to translate the examples to work with ORBIT >= 1.0.0

It looks like the pre-commit hooks did some formatting, so let me know if we should try to shorten up any of the lines for aesthetic purposes.

No new tests were added as the additions did not seem to warrant them.

Let me know if there are any more details needed or if there are any questions/concerns with the additions.

### CODE REVIEW

**Comment by JakeNunemaker** [comment]
I'm not sure what's going on with the tests actions. I've looked into it a little bit and I think it's an intermittent issue on their end. In the meantime I'm running the tests locally and playing around with it.

**Comment by JakeNunemaker** [comment]
@RHammond2 Overall this looks good but I did get this error occasionally:

Screen Shot 2021-04-05 at 5 28 24 PM

I'm assuming that attribute isn't set if there isn't a partial string?

**Comment by JakeNunemaker** [comment]
@Matt-Shields FYI

**Comment by RHammond2** [comment]
Thanks for taking a look, @JakeNunemaker , I've pushed a small change that should fix that error for layouts that don't have any partial strings.

**Comment by JakeNunemaker** [comment]
@RHammond2 Thanks Rob!

**Review by JakeNunemaker — APPROVED** [review]

**Pull request merged**
