### PR TITLE
Enhancement/custom array cables

### PR DESCRIPTION
**Pull request by RHammond2**
This pull request creates an examples folder to be used for the GitHub based examples and the first example where the capability of using customized array cable layouts is demonstrated. In addition there are a few small bugs that were fixed in the calculations as well as a small amount of cleaning up.

### CODE REVIEW

**Comment by JakeNunemaker** [comment]
@RHammond2 This looks really good - the detail on the tutorial is great. I made a few small language edits and changed the "turbine" definitions to "SWT_6MW_154m_110m".

**Comment by JakeNunemaker** [comment]
The only other comment I had was this attribute:
Screen Shot 2020-04-30 at 7 08 10 PM

What do you think about changing it to `array.location_data` or something along those lines?

**Comment by JakeNunemaker** [comment]
Oh, the other thing that I forgot to mention last night:

I worry about adding another library to the examples folder that we need to manage - could we store the example .csv's in the repo level library folder and use other resources of the repo level library? That way we'll just have the ORBIT/library and ORBIT/tests/library (which makes sense to keep separate for testing purposes).

**Comment by RHammond2** [comment]
@JakeNunemaker I used the examples library folder because I assumed you wouldn't want the example data there, but more than happy to move it to the repo level folder because it's definitely way easier to maintain it in one spot. Happy to change the variable name too; I wasn't sold on it myself, but didn't have a great alternative in mind at the time!

**Comment by JakeNunemaker** [comment]
I think it's fine to go in the top level library as long as the data is public.

Does this work within `ProjectManager`?

**Comment by RHammond2** [comment]
I'll add a `ProjectManager` example to the notebook and make sure it works if that would be useful.

**Comment by JakeNunemaker** [comment]
You could also modify the last section in the tutorial to run 'CustomArraySystemDesign' and `ArrayCableInstallation` module from `ProjectManager`.

**Comment by RHammond2** [comment]
@JakeNunemaker that should be all. The `CustomArrayDesign` wasn't in `ProjectManager` but it should work now; at least the example I've used does. There is one test that doesn't pass and put the information in the screenshot below. Do you have any idea what this could be from?
image

**Comment by JakeNunemaker** [comment]
Oh I think that might be on my end in a small fix I pushed yesterday afternoon. Let me check.

**Comment by JakeNunemaker** [comment]
Yep - that was from a small naming change Matt and I made yesterday. I'll push a quick fix to dev.

**Comment by JakeNunemaker** [comment]
@Matt-Shields Did you want to look at this before its merged? We don't need to yet, just before the meeting next Wednesday.

**Comment by Matt-Shields** [comment]
@JakeNunemaker @RHammond2 thanks for pulling this together - i would like to look it over before merging, but won't get to it until this weekend or monday.  if it gets to the end of the day monday and i haven't responded, go ahead and merge it in.

**Comment by RHammond2** [comment]
Thanks for the comments, Matt. A couple of comments below:
* I can update the title of 2b, which is using distance as a relative coordinate system so that this is more clear when reading through the notebook. I included the part where I actually convert from lat/lon to some relative distance measure so that others could also know how to do this. This allows a user to utilize a relative (anonymous/privacy-preserving) positioning via distance from a point vs an absolute (exact placement on the globe) positioning of their turbines.
* I'll go through the other identified examples to make sure that it is abundantly clear what is going on between each step.
* I'll be sure to add a specific note that the Dudgeon data is publicly accessible, though I extracted it specifically for this example.
* I'll add in some more commentary around the use of YAML and CSV files for configuration before I jump into the examples also.

**Comment by Matt-Shields** [comment]
I think the issues is that, in your 2b use case, the user still needs to know the original position of the turbines in lat/lon coordinates.  in my opinion, this is not necessarily always the case.  I am suggesting removing the entire haversine_distance method from the example and just demonstrating that the user can input the lat2new and lon2new values directly, presumably using the same approach as the exact lat/lon values input in Case 1.  i don't think that latitude or longitude should appear at all in this use case.

**Comment by RHammond2** [comment]
Ok, I guess I was struggling with wrapping my head around the idea of having unknown positioning of turbines.

See the most recent commit for my updates. I'm not sure we can remove latitude/longitude because those are still column names,  it's just that they represent distances, which I have noted. Let me know if the updates help clear up any confusion.

**Comment by JakeNunemaker** [comment]
What about having the column names dictate which method is used? If lat/lon are found, use the haversine distance with the coords. If the column names are renamed to x/y, use euclidean. If for some reason both are in there, use lat/lon as it is more explicit.

**Comment by RHammond2** [comment]
I had already added the `distance` flag in the config and kwargs for `CustomArraySystemDesign` to indicate this. Though I should actually update the text to specifically call this out better (commit forthcoming), but having a dual encoding is quite a bit more work and adds a fair amount of complexity than just a set column name.

Alternatively, we could just switch the column names to "x" and "y" from "longitude" and "latitude", respectively, while still maintaining the distance flag. This solution would be far easier (personally preferred also), but still take a bit of effort because there are multiple references throughout the class and all the documentation would need to be updated.

**Comment by JakeNunemaker** [comment]
The dual encoding solution would be more explicit. To me a `distance` flag would be easier to forget than incorrectly labeling your columns lat,lon when you meant x,y.

I'm happy to defer the decision to you guys though - just my perspective. Also, for the sake of time, maybe we should keep it as is and come back to if needed.

**Comment by Matt-Shields** [comment]
I suggest making the quickest change we can.  I'm fine with labeling the columns x and y for now, we can always modify later.  but ideally we would like to push this into the shell repo today (if it's ready).

**Comment by JakeNunemaker** [comment]
Let's keep the columns lat, lon for now with the distance flag - that shouldn't require any change, right?

@RHammond2 Is this good to merge then?

**Comment by RHammond2** [comment]
My only qualm with your solution was the time commitment; it's definitely the more robust to ease of use! If you're ok with me not being able to complete it until either later this week or earlier next week, then I'm happy to work on this one. My outlook for this week is not great due to a few other projects taking up time on my schedule.

**Comment by RHammond2** [comment]
Sorry, didn't see there were updates here, yes, this is good to merge right now with a distance flag.

**Pull request merged**
